# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

animations {
    enabled = yes

    # smooth but a little dramatic
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = overshot, 0.05, 0.9, 0.1, 1.08

    # window motion
    animation = windows, 1, 5, overshot, slide
    animation = windowsIn, 1, 6, overshot, popin
    animation = windowsOut, 1, 5, default, popin
    animation = windowsMove, 1, 4, easeOutQuint, slide

    # subtle extras
    animation = fade, 1, 4, easeOutQuint
    animation = border, 1, 8, default
    animation = borderangle, 1, 12, default, once

    animation = workspaces, 1, 6, overshot, slide


    bezier = bounce, 0.68, -0.55, 0.27, 1.55
    animation = windowsIn, 1, 6, bounce, popin
}
