-- Omarchy Custom Theme for Neovim
-- Generated by Omarchist

return {
  {
    "tahayvr/sunset-drive.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      vim.cmd.colorscheme("sunsetdrive")
    end,
  },
}
